# Generated by Django 4.2 on 2025-12-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_plan_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
