# Generated by Django 4.2 on 2025-11-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=20)),
                ('poster', models.URLField()),
                ('backdrop', models.URLField()),
                ('genre', models.CharField(max_length=200)),
                ('languages', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_action', models.BooleanField(default=False)),
                ('is_malayalam', models.BooleanField(default=False)),
                ('is_scifi', models.BooleanField(default=False)),
                ('is_comedy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
