# Generated by Django 4.2 on 2025-11-30 06:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
