# Generated by Django 4.2 on 2025-12-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
