# Generated by Django 4.2 on 2025-12-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_file',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
